# 製品イメージを使用した展開

version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
    restart: always
    environment:
      DOMAINS: "localhost -> http://frontend:3000"
      STAGE: local
      # STAGE: 'production'
      # FORCE_RENEW: 'true'

  # Application-Backend
  backend:
    image: my-nest-js-app
    depends_on:
      - db
    environment:
      API_PORT: 4000
      # DB_LOGGING: "FALSE"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: database
      DB_USERNAME: username
      DB_PASSWORD: password
    # ports:
    #   - 4000:4000

  # Application-Frontend
  frontend:
    image: my-next-js-app
    depends_on:
      - backend
    # environment:
    #   SITE_URL: http://192.168.11.5
    #   SITE_PORT: 3000
    #   API_URL: http://backend
    #   API_PORT: 4000
    #   NEXT_PUBLIC_SITE_URL: "this is public variable!!"
    # ports:
    #   - 80:3000

  # MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: username
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 300M
    ports:
      - 8010:80
